interface Settings {
  phoneSettings: {
    language: string | null,
    timezone: string | null,
    dst: string | null,
    userActive: boolean | null,
    userRealName: string | null,
    userName: string | null,
    userHost: string | null,
    userOutbound: string | null,
    userPass: string | null,
    userSRTP: boolean | null,
    userMailbox: string | null,
    toneScheme: string | null,
    provisioningOrder: string[] | null,
    codecPriorityList: string[] | null,
    adminModePass: string | null,
    httpUser: string | null,
    httpPass: string | null,
    uiTheme: string | null,
    fk0Context: string | null,
    fk0Type: string | null,
    fk0Number: string | null,
    fk0Label: string | null,
    fk1Context: string | null,
    fk1Type: string | null,
    fk1Number: string | null,
    fk1Label: string | null,
    fk2Context: string | null,
    fk2Type: string | null,
    fk2Number: string | null,
    fk2Label: string | null,
    fk3Context: string | null,
    fk3Type: string | null,
    fk3Number: string | null,
    fk3Label: string | null,
    fk4Context: string | null,
    fk4Type: string | null,
    fk4Number: string | null,
    fk4Label: string | null,
    fk5Context: string | null,
    fk5Type: string | null,
    fk5Number: string | null,
    fk5Label: string | null,
  }
};

export type { Settings };